### ISSUE TITLE
 CLR/CLP Calculation for PE and SE Reads

### ISSUE THREAD

**Issue by ChengxuanChen10** [egaffo/circompara2#27]
Hello,

On the wiki page, there's a mention of the calculation of the circular-to-linear expression ratio (CLR) and the circular-to-linear expression proportion (CLP) with formulas presented as follows:
CLR = BJR / LSRBJ
CLP = BJR / (LSRBJ + BJR)

Should the formula for CLR differ between paired-end (PE) reads and single-end (SE) reads, as CLR = 2*BJR / LSRBJ for PE reads and CLR = BJR / LSRBJ for SE reads?

**Comment by egaffo** [comment]
Not really. 
The read bearing the backsplice junction (BSJ) is (almost) always only one of the two read mates; therefore, you don't want to count the mate that does not contain the BSJ.
Moreover, the counts reported by CirComPara2 refer to sequenced fragments, i.e., read pairs.
You may have found the formula CLR = 2*BJR / LSRBJ in some papers, but, to my understanding, it was not due to PE reads. I think the BJRs are counted twice because you are comparing two different splice points (the LSBJs, which will have different reads encompassing the splice junctions) against one splice point that actually includes two canonical splice points.
In my opinion, the CLR = 2*BJR / LSRBJ interpretation is legit.

**Comment by ChengxuanChen10** [comment]
Thank you!
